//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using CTShared.Cards;
using CTShared.Networking;

namespace CTShared
{
public abstract partial class Card : Packet
{
	private readonly static ImmutableDictionary<string, Type> namesToCards = new Dictionary<string, Type>
	{
		{ "Abhor", typeof(Abhor) },
		{ "Anchorage", typeof(Anchorage) },
		{ "Ancient", typeof(Ancient) },
		{ "Barrier", typeof(Barrier) },
		{ "Bulwark", typeof(Bulwark) },
		{ "Devise", typeof(Devise) },
		{ "Flaming", typeof(Flaming) },
		{ "Grim", typeof(Grim) },
		{ "Heart", typeof(Heart) },
		{ "Hound", typeof(Hound) },
		{ "Lock", typeof(Lock) },
		{ "Priest", typeof(Priest) },
		{ "Prince", typeof(Prince) },
		{ "Prophet", typeof(Prophet) },
		{ "Refuse", typeof(Refuse) },
		{ "Sunset", typeof(Sunset) },
		{ "Sword", typeof(Sword) },
		{ "TwoFaced", typeof(TwoFaced) },
		{ "Unveil", typeof(Unveil) },
		{ "Weary", typeof(Weary) },
		{ "Year", typeof(Year) },
		{ "Zealot", typeof(Zealot) },
	}.ToImmutableDictionary();
}
}
